update workflows & change eval to exec

diff --git a/.github/workflows/_build.yml b/.github/workflows/_build.yml
--- a/.github/workflows/_build.yml
+++ b/.github/workflows/_build.yml
@@ -3,28 +3,59 @@ name: Build
 on:
   workflow_call:
     inputs:
-      tag:
+      image:
         type: string
         required: true
-      name:
+      registry:
         type: string
-        required: true
-
-env:
-  REGISTRY: ghcr.io
+        required: false
+        default: ghcr.io
+      container_file_name:
+        type: string
+        required: false
+        default: Dockerfile
 
 permissions:
   actions: read
   packages: write
 
 jobs:
-  build:
-    name: ${{ inputs.tag }}
+  prepare-tags:
+    name: Getting tags
     runs-on: ubuntu-latest
-    env:
-      TAG: ${{ inputs.tag }}
-      NAME: ${{ inputs.name }}
-      CONTEXT: ${{ inputs.context }}
+    outputs:
+      matrix: ${{ steps.matrix-list.outputs.matrix }}
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Getting tags
+        id: matrix-list
+        run: |
+          image="${{ inputs.image }}"
+          
+          if [ ! -d "$image" ]; then
+            echo "Error: Folder '$image' does not exist!"
+            exit 1
+          fi
+          
+          versions=$(find "$image" -mindepth 1 -maxdepth 1 -type d -printf "%f\n" | jq -R '.' | jq -s '.' -c)
+          
+          if [ "$(echo "$versions" | jq '. | length')" == 0 ]; then
+            echo "No versions found in '$image'!"
+            exit 1
+          fi
+          
+          echo "matrix=$versions" >> $GITHUB_OUTPUT
+
+  build:
+    runs-on: ubuntu-latest
+    needs: prepare-tags
+    strategy:
+      matrix:
+        tag: ${{fromJson(needs.prepare-tags.outputs.matrix)}}
+      fail-fast: false
+    name: Build ${{ inputs.image }}-${{ matrix.tag }}
     steps:
       - name: Checkout
         uses: actions/checkout@v4
@@ -32,18 +63,18 @@ jobs:
       - name: Setup BuildX
         uses: docker/setup-buildx-action@v3
 
-      - name: Login to ${{ env.REGISTRY }}
+      - name: Login to ${{ inputs.registry }}
         uses: docker/login-action@v3
         with:
-          registry: ${{ env.REGISTRY }}
+          registry: ${{ inputs.registry }}
           username: ${{ github.repository_owner }}
           password: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Build and push image
         uses: docker/build-push-action@v5
         with:
-          context: ${{ env.NAME }}
-          file: ${{ env.NAME }}/${{ env.TAG }}/Dockerfile
+          context: ${{ inputs.image }}
+          file: ${{ inputs.image }}/${{ matrix.tag }}/${{ inputs.container_file_name }}
           platforms: linux/amd64
           push: true
-          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/pterodactyl-images/${{ env.NAME }}:${{ env.TAG }}
+          tags: ${{ inputs.registry }}/${{ github.repository_owner }}/pterodactyl-images/${{ inputs.image }}:${{ matrix.tag }}
